language: python
cache:
  - "pip"
  - "yarn"
python:
  - "3.7-dev"
install:
  - "pip install pipenv"
  - "pipenv install --dev"
script:
  - "pipenv check"
  - "yarn lint"
  - "yarn test"
after_success:
  - "pipenv run coveralls"
deploy:
  provider: "pypi"
  distribution: "sdist"
  skip_cleanup: true
  user: __token__
  password:
    secure: r8XqIhXMNrj3Z0bM8+kO0K4aCVPm54Kp7ZUVntrO/SRfRdyECOodkhAxsn3MY0Nv2MW3rkDX1gnNkR+rTP5U36nPNI4w7u6jlVVasO70sebEKYoJFhVclqylptx6PEuFXjdRM5Ic3ba/oR+9Jizo8XIbwz6v50wMxDy+cJehXufkVbs/E7JxYjRUIskRO3ghnYmbD3Vaqn66eFJrqaYirNkTM8Jk2Mj4nQlPam2IhIFICEXyDXZQ89ELgrGqGwNcQphzylh+eqjB/CRDz5ojhfX8dKktXDJKacJfbzDvBYBZXV/1WxOJt7/sD3JkWLK3hYHxXS6TgSAm3ZJsE1/f/msOZcekR4LqsSquzD1qtLx8sAZ0yKDbFMx1A7iigf48sllqdM4tE2oeKWFTzR9zbNattvY+SFg88fxSxNpZ/iwxqrwBFdY8rwfH0IYsjUn27mOBUakMhC/R/n5Vx2tYz971U+uNNgPGzXQWyvqd5GFpQvpD1IVKjVgPkY8Q0hWRXNf/DY/hH5Qa8m7fgZm0muwM/ncp/A+k/AolEZK5Xx+2scC8bas/D0FWCTf14sHhyR74RmD47rMHL1kcZYQMFdGKM1hLKg7Khq2CkiEBeqtxbVf+mSMKv9rp4Ntb0v+lrgIxCC8Qkmlt0TnKsL5j7/eui3B8p7Um1DAnXT8Wnm8=
  on:
    tags: true
